config/routes.rb
Rails.application.routes.draw do
  resources :user_achievements
	root to: 'users#index'
  resources :trainings
  resources :achievements
  resources :words
  devise_for :users
  get '/users/:id', to: 'users#show', as: 'user'
  get 'users/:user_id/trainings/:id/train', to: 'trainings#train', as: 'train'
  get '/api/trainings/:id/words', to: 'api_words#get_words', as: 'get_words'
  get '/api/trainings/:id/results', to: 'api_words#get_results', as: 'get_results'
  post '/api/trainings/:training_id/words/:word_id/check', to: 'api_words#check'
  get "/cheat", to: 'api_words#cheat', as: 'cheat'
  match '/contacts',     to: 'contacts#new',             via: 'get',  :as => :contact
resources "contacts", only: [:new, :create]

get "/:page" => "static#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
	belongs_to :user
	has_many :training_words
	has_many :words, through: :training_words

	def filter_words(tier, topic, stages, word_types)

		# filter by stage
		
		word_filters = {}
		word_filters[:tier] = "foundation" if tier == "foundation"
		word_filters[:topic] = topic unless topic == "all"
		word_filters[:word_type] = word_types unless word_types == "all word types"  
		words_to_train = Word.where(word_filters).left_outer_joins(user_words: :user).where("user_words.user_id = ? OR user_words.user_id IS NULL", user.id)
		
		unless stages == "all stages"
			words_to_train = words_to_train.where(user_words: {stage: stages.to_i})
		end


		
		return words_to_train

	end

	def filter_tier(tier)
		tier == "foundation" ? words_to_train = words_to_train.select {|w| w.tier == "foundation"} : words_to_train
	end

	def filter_topics(topic)
		topic == "all" ? words_to_train : words_to_train = words_to_train.select {|w| w.topic == topic}
	end

	# def filter_stages(stages)
	# 	case stages
	# 	when "unseen"
	# 		words_to_train = words_to_train.select {|w| w.stage == nil}
	# 	when "0"
	# 		words_to_train = words_to_train.select {|w| w.stage == 0}
	# 	when "1"
	# 		words_to_train = words_to_train.select {|w| w.stage == 1}
	# 	when "2"
	# 		words_to_train = words_to_train.select {|w| w.stage == 2}
	# 	when "3"
	# 		words_to_train = words_to_train.select {|w| w.stage == 3}
	# 	when "4"
	# 		words_to_train = words_to_train.select {|w| w.stage == 4}
	# 	else
	# 		words_to_train
	# 	end
	# end

	def filter_word_types(word_types)
		word_types == "all word types" ? words_to_train : words_to_train = words_to_train.select {|w| w.word_type == word_types}
	end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

	def new
		@training = Training.new
	end

	def create
	    user = User.find_by(id: params[:user_id])

	    @tier = params[:tier]
	    @topic = params[:topic]
	    @stage = params[:stage]
	    @word_type = params[:word_type]

	    training = Training.new(user: current_user, topic: @topic, tier: @tier, stage: @stage, word_type: @word_type)

	    @words = training.filter_words(@tier, @topic, @stage, @word_type)
	    	if @words.length < 10
	    		flash[:notice] = "There aren't enough words that fit your selection. Try a different combination."
    			redirect_to new_training_path
    		else
    			training.save
	    		@words = @words.shuffle
	    		@words = @words.take(10)
	    		training.words = @words
	    		redirect_to training_path(training)
	    	end
    end

    def show
    	@user = current_user
    	@training = Training.find_by(id: params[:id])
    	@words = @training.training_words
    	redirect_to user_path(@user) if @training.user_id != @user.id
    	# @stages = @words.each do |word|
    	# 			word.stage_for_user
    	# 			end
    	# @stages = []
    	# @words.each do |word|
    	# 	this_word = @user.user_words.find_by_id(word.id)
  			# 	if this_word == nil
  			# 		stage = nil
  			# 	else
  			# 		stage = this_word.stage
  			# end
  			# @stages.push(stage)
  		# end
    end

    def train
    	@user = User.find_by(id: params[:user_id])
    	@training = Training.find_by(id: params[:id])
    	@words = @training.training_words
    	@words.each do |w|
    		this_word = @user.user_words.find_by(word_id: w.word_id)
    		unless this_word
    			new_word = @user.user_words.create(word: w.word, stage: 0)
				new_word.save
			end
		end
    end

    def my_api_method
    	render json: {result: "incorrect"}
    end


end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/new.html.erb
<div class="container-fluid new-training">
	<div class="row">
			<h1>Let's train</h1>
		<div class="col-lg-12 training-form">


    <%= form_for [@training] do |f| %>
        <% if @training.errors.any? %>
         <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this training from being created:</h2>

            <ul>
              <% @training.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
           </ul>
         </div>
        <% end %>
        <% if flash[:notice] %>
    		<div class="notice" style="color:red"><%= flash[:notice] %></div>
  		<% end %>
		<h2>What do you want to train today?</h2>
		<% time = Time.now %>
		<% case time.wday %>
		<% when 0 %>
			<h5 style="color:green"><strong>Daily Challenge: triple points for Leisure today!</strong></h5>
		<% when 1 %>
			<h5 style="color:green"><strong>Daily Challenge: triple points for Key Words today!</strong></h5>
		<% when 2 %>
			<h5 style="color:green"><strong>Daily Challenge: triple points for verbs today!</strong></h5>
		<% when 3 %>
			<h5 style="color:green"><strong>Daily Challenge: triple points for nouns today!</strong></h5>
		<% when 4 %>
			<h5 style="color:green"><strong>Daily Challenge: triple points for Education today!</strong></h5>
		<% when 5 %>
			<h5 style="color:green"><strong>Daily Challenge: triple points for Me, My Family and Friends today!</strong></h5>
		<% else %>
			<h5 style="color:green"><strong>Daily Challenge: triple points for Home and Local Area today!</strong></h5>
		<% end %>

       
        <div class="field">
        	<h4>Topics</h4>
				<span style="white-space:nowrap">
        		<%= radio_button_tag(:topic, "all", :checked) %>
				<%= label_tag(:all, "All topics")  %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
          		<%= radio_button_tag(:topic, "key words") %>
				<%= label_tag(:key_words, "General key words") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "connectives") %>
				<%= label_tag(:connectives, "Connectives") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "prepositions") %>
				<%= label_tag(:prepositions, "Prepositions") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "opinions") %>
				<%= label_tag(:opinions, "Opinions") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "travel and tourism") %>
				<%= label_tag(:travel_and_tourism, "Travel and Tourism") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "home and local area") %>
				<%= label_tag(:local_area, "Home and local area") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "me, my family and friends") %>
				<%= label_tag(:me_my_family_and_friends, "Me, my family and friends") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "technology") %>
				<%= label_tag(:technology, "Technology") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "leisure") %>
				<%= label_tag(:leisure, "Leisure") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "festivals") %>
				<%= label_tag(:festivals, "Festivals") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "health and social issues") %>
				<%= label_tag(:health_and_social_issues, "Health and Social Issues") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "global issues") %>
				<%= label_tag(:global_issues, "Global Issues") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "education") %>
				<%= label_tag(:education, "Education") %>
				</span>
				&emsp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:topic, "work") %>
				<%= label_tag(:work, "Work") %>
				</span>
          </div>

        <div class="field">
        	<h4>Stage</h4>
        		<span style="white-space:nowrap">
        		<%= radio_button_tag(:stage, "all stages", :checked) %>
				<%= label_tag(:any_stage, "A mixture of stages") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:stage, "0") %>
				<%= label_tag(:zero, "Words I haven't got right yet") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:stage, "1") %>
				<%= label_tag(:one, "Stage 1 words") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:stage, "2") %>
				<%= label_tag(:two, "Stage 2 words") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:stage, "3") %>
				<%= label_tag(:three, "Stage 3 words") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:stage, "4") %>
				<%= label_tag(:four, "Stage 4 words") %>	
				</span>			
        </div>

        <div class="field">
        	<h4>Type of word</h4>
        		<span style="white-space:nowrap">
        		<%= radio_button_tag(:word_type, "all word types", :checked) %>
				<%= label_tag(:all_word_types, "A mixture of word types") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:word_type, "verb") %>
				<%= label_tag(:verb, "Only verbs") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:word_type, "noun") %>
				<%= label_tag(:noun, "Only nouns") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:word_type, "adjective") %>
				<%= label_tag(:adjective, "Only adjectives") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:word_type, "preposition") %>
				<%= label_tag(:preposition, "Only prepositions") %>
				</span>
				&ensp;
				<span style="white-space:nowrap">
				<%= radio_button_tag(:word_type, "other") %>
				<%= label_tag(:other, "Only other types of words") %>
				</span>				
        </div>

        <input type="hidden" name="user_id" value=<%= current_user.id %>>
        <input type="hidden" name="tier" value=<%= current_user.tier %>>

          <div class="actions">
          	<br>
            <%= f.submit "Let's go!"%>
          </div>
    <% end %>
    	</div>
    </div>
 </div>

app/views/trainings/show.html.erb
<div class="container-fluid new-training">
	<div class="row">
			<h1><%= @user.name %>'s Training Session</h1>
		<div class="col-lg-12 training-form">
			<div class="training-details">
				<h3><%= @training.name %></h3>
				<small><%= @training.updated_at.strftime("%d %b %y") %></small>
			</div>

			<div class="training-words table-responsive">
				<h4>Topic:&nbsp;<%= @training.topic %>
				&emsp;&emsp;&emsp;Stage:&nbsp;<%= @training.stage %>
				&emsp;&emsp;&emsp;Word Types:&nbsp;<%= @training.word_type %></h4>
				<table class="display-trainings table-striped">
					<tr>
    					<th class="table-headings">German</th>
    					<th class="table-headings">English</th>
    					<th class="table-headings">Word Type</th>
    					<th class="table-headings">Current Stage</th>
    					<th class="table-headings">Most Recent Result</th>
  					</tr>
					<% @words.each do |w| %>
					<tr>
						<td class="words-to-train"><%= w.word.tl %></td>
						<td class="words-to-train"><%= w.word.english %></td>
						<td class="words-to-train"><%= w.word.word_type %></td>
						<td class="words-to-train"><% this_word = w.word.user_words.find_by(user_id: @user).try!(:stage) %>
													<% if this_word == nil %>
														You haven't seen this word yet.
													<% else %>
														<%= this_word %>
													<% end %>
						</td>
						<td class="words-to-train"><% if w.result == true %>
														Correct
													<% elsif w.result == false %>
														Incorrect
													<% else %>
														You haven't seen this word yet.
													<% end %>
						</td>
					</tr>
					<% end %>
				</table>
			</div>

			<%= button_to "I'm ready!", train_path(@user.id, @training.id), :method => "get", :class => "btn btn-default btn-md" %>
		</div>
	</div>
</div>

app/views/trainings/train.html.erb
<div class="container-fluid new-training">
	<div class="row">
			<h1><%= @user.name %>'s Training Session</h1>
		<div class="col-lg-12 training-form">
			<div class="training-details">
				<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#tips" style="float:right">Tips</button>
				<br>
				<h3><%= @training.name %></h3>
				<small><%= @training.updated_at.strftime("%d %b %y") %></small>
			</div>
			

			<% @words.each_with_index do |w, i| %>
				<% q_num = i + 1 %>
				<% this_word = @user.user_words.find_by(word_id: w.word_id) %>
				<div class="training-<%= q_num %>">
					<div class="training-question">
						<% if this_word %>
							<% if this_word.stage >= 4 %>
								<h1>Q<%= q_num %>. <strong><%= w.word.english %></strong></h1>
								<h5><em>Type of word: <%= w.word.word_type %></em></h5>
								<h3>What is the German?</h3>
								<div class="training-answer">
									<form class="answer-question-<%= q_num %>" method="POST">
										<input type="text" name="q<%= q_num %>-answer" id="q<%= q_num %>-answer" placeholder="Your answer" autocomplete="off">
										<input type="hidden" class="js-answer" name="js-q<%= q_num %>-answer" id="<%= w.word_id %>">

										<button id="submit" type="submit" name="button">Submit</button>
										<%= render "umlauts" %>
									</form>
								</div>
							<% elsif this_word.stage == 2 || this_word.stage == 3 %>
								<h1>Q<%= q_num %>. <strong><%= w.word.english %></strong></h1>
								<h5><em>Type of word: <%= w.word.word_type %></em></h5>
								<h3>What is the German?</h3>
								<h3><em><%= w.word.tl.gsub(/\B\w+\B/){$&.split(//).sort_by{rand}.join} %></em></h3>
								<div class="training-answer">
									<form class="answer-question-<%= q_num %>" method="POST">
										<input type="text" name="q<%= q_num %>-answer" id="q<%= q_num %>-answer" placeholder="Your answer" autocomplete="off">
										<input type="hidden" class="js-answer" name="js-q<%= q_num %>-answer" id="<%= w.word_id %>">

										<button id="submit" type="submit" name="button">Submit</button>
										<%= render "umlauts" %>
									</form>
								</div>
							<% else %>
								<h1>Q<%= q_num %>. <strong><%= w.word.english %></strong></h1>
								<h5><em>Type of word: <%= w.word.word_type %></em></h5>
								<h3>What is the German?</h3>
								<div class="training-answer">
									<% poss_words = [] %>
									<% until poss_words.length == 3 %>
										<% a_word = @words.sample %>
										<% if a_word != w && poss_words.include?(a_word) == false %>
											<% poss_words.push(a_word) %>
										<% end %>
									<% end %>
									<% poss_words.push(w) %>
									<form class="answer-question-<%= q_num %>" method="POST">
										<div class="btn-group " data-toggle="buttons">

										<% poss_words.shuffle.each do |pw| %>
											<label class="btn btn-primary multiple-choice">
											<input type="radio" name="q<%= q_num %>-answer" value="<%= pw.word.tl%>" ><%= pw.word.tl %>
											 </label>
										<% end %>
										<input type="hidden" class="js-answer" name="js-q<%= q_num %>-answer" id="<%= w.word_id %>">
										</div>
										<br><br>
										<button id="submit" type="submit" name="button">Submit</button>
									</form>
								</div>				

							<% end %>
						<% end %>
					</div>

					<div class="response">
					</div>
				</div>

			<% end %>
			<!-- <div class="training-1">
				<div class="training-question">
					<h3>Question 1 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-1" method="POST">
      					<input type="text" name="q1-answer" id="q1-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer" name="js-q1-answer">

      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-2">
				<div class="training-question">
					<h3>Question 2 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-2">
      					<input type="text" name="q2-answer" id="q2-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer" name="js-q2-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-3">
				<div class="training-question">
					<h3>Question 3 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-3" method="POST">
      					<input type="text" name="q3-answer" id="q3-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-4">
				<div class="training-question">
					<h3>Question 4 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-4" method="POST">
      					<input type="text" name="q4-answer" id="q4-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-5">
				<div class="training-question">
					<h3>Question 5 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-5" method="POST">
      					<input type="text" name="q5-answer" id="q5-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-6">
				<div class="training-question">
					<h3>Question 6 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-6" method="POST">
      					<input type="text" name="q6-answer" id="q6-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-7">
				<div class="training-question">
					<h3>Question 7 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-7" method="POST">
      					<input type="text" name="q7-answer" id="q7-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-8">
				<div class="training-question">
					<h3>Question 8 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-8" method="POST">
      					<input type="text" name="q8-answer" id="q8-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-9">
				<div class="training-question">
					<h3>Question 9 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-9" method="POST">
      					<input type="text" name="q9-answer" id="q9-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div>

			<div class="training-10">
				<div class="training-question">
					<h3>Question 10 will go here</h3>
				</div>
				<div class="training-answer">
					<form class="answer-question-10" method="POST">
      					<input type="text" name="q10-answer" id="q10-answer" placeholder="Your answer">
						<input type="hidden" class="js-answer">
      					<button id="submit" type="submit" name="button">Submit</button>
    				</form>
				</div>
				<div class="response">
				</div>
			</div> -->

			<div class="results">
			</div>

			
		</div>
	</div>
</div>
<div class="modal fade" id="tips" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		<div class="modal-content">
				<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">Tips for answering questions</h4>
				</div>
				<div class="modal-body">
					 <ul>
					 	<li>You need to include the correct gender for nouns (der / die / das). It might be annoying but you need to know them.</li>
					 	<br>
					 	<li>Nouns need to have a capital letter.</li>
					 	<br>
					 	<li>If the noun refers to a person, Linguathon uses the masculine version by default (eg 'der Lehrer' rather than 'die Lehrerin').</li>
					 	<br>
					 	<li>Use the plain version of adjectives, with no agreements (eg 'gelb')</li>
					 	<br>
					 	<li>For adverbs, Linguathon uses the masculine/nominative version by default (eg 'welcher')</li>
					 	<br>
					 	<li>You need to include umlauts and special characters. Use the buttons to insert them.</li>
					 	<br>
					 	<li>Look carefully at the word type to help you. There's a difference between 'a present' (noun), 'present' (adjective) and 'to present' (verb), for example.</li>
					 </ul>
				</div>
				<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
		</div>
		</div>
</div>
<script>
	var id = <%= @training.id %>
</script> 