config/routes.rb
Rails.application.routes.draw do
  resources :user_achievements
	root to: 'users#index'
  resources :trainings
  resources :achievements
  resources :words
  devise_for :users
  get '/users/:id', to: 'users#show', as: 'user'
  get 'users/:user_id/trainings/:id/train', to: 'trainings#train', as: 'train'
  get '/api/trainings/:id/words', to: 'api_words#get_words', as: 'get_words'
  get '/api/trainings/:id/results', to: 'api_words#get_results', as: 'get_results'
  post '/api/trainings/:training_id/words/:word_id/check', to: 'api_words#check'
  get "/cheat", to: 'api_words#cheat', as: 'cheat'
  match '/contacts',     to: 'contacts#new',             via: 'get',  :as => :contact
resources "contacts", only: [:new, :create]

get "/:page" => "static#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :user_words
  has_many :words, through: :user_words
  has_many :trainings

  has_many :user_achievements
  has_many :achievements, through: :user_achievements

  has_streak

  after_create :send_welcome_email

    def has_achievement?(achievement)
    	achievements.find_by(name: achievement)
    end

    def award_achievement(achievement)
    	new_a = user_achievements.create(achievement: Achievement.find_by(name: achievement))
    	new_a.save
    end

    def check_achievements
    	streak_achievements
    	words_achievements
    	topic_achievements
    	misc_achievements
    	one_of_each
    end

    def streak_achievements
    	streak = streak(:trainings)
    	if streak
	    	if streak >= 1 && !has_achievement?("1st")
	    		# new_achievements.push("1st")
	    		award_achievement("1st")
	    	elsif streak >= 2 && !has_achievement?("2days")
	    		award_achievement("2days")
	    	elsif streak >= 3 && !has_achievement?("3days")
	    		award_achievement("3days")
	    	elsif streak >= 5 && !has_achievement?("5days")
	    		award_achievement("5days")
	    	elsif streak >= 7 && !has_achievement?("7days")
	    		award_achievement("7days")
	    	elsif streak >= 14 && !has_achievement?("2weeks")
	    		award_achievement("2weeks")
	    	elsif streak >= 21 && !has_achievement?("3weeks")
	    		award_achievement("3weeks")
	    	elsif streak >= 28 && !has_achievement?("1month")
	    		award_achievement("1month")
	    	end
	    end
    end

    def words_achievements
    	total_words = words.length

    	if total_words >= 10 && !has_achievement?("10words")
    		award_achievement("10words")
    	elsif total_words >= 25 && !has_achievement?("25words")
    		award_achievement("25words")
    	elsif total_words >= 50 && !has_achievement?("50words")
    		award_achievement("50words")
    	elsif total_words >= 100 && !has_achievement?("100words")
    		award_achievement("100words")
    	elsif total_words >= 250 && !has_achievement?("250words")
    		award_achievement("250words")
    	elsif total_words >= 500 && !has_achievement?("500words")
    		award_achievement("500words")
    	elsif total_words >= 1000 && !has_achievement?("1000words")
    		award_achievement("1000words")
    	elsif total_words >= 1500 && !has_achievement?("1500words")
    		award_achievement("1500words")	
    	elsif total_words >= 1600 && !has_achievement?("allwords")
    		award_achievement("allwords")
    	end

    end

    def topic_achievements
    	if words.where(topic: "key words").length == 226 && !has_achievement?("keywords")
    		award_achievement("keywords")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "connectives").length == 42 && !has_achievement?("connectives")
    		award_achievement("connectives")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "prepositions").length == 17 && !has_achievement?("prepositions")
    		award_achievement("prepositions")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "opinions").length == 77 && !has_achievement?("opinions")
    		award_achievement("opinions")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "travel and tourism").length == 169 && !has_achievement?("travel")
    		award_achievement("travel")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "home and local area").length == 205 && !has_achievement?("home")
    		award_achievement("home")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "me, my family and friends").length == 147 && !has_achievement?("me")
    		award_achievement("me")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "technology").length == 45 && !has_achievement?("technology")
    		award_achievement("technology")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "leisure").length == 192 && !has_achievement?("leisure")
    		award_achievement("leisure")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "festivals").length == 47 && !has_achievement?("festivals")
    		award_achievement("festivals")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "health and social issues").length == 108 && !has_achievement?("health")
    		award_achievement("health")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "global issues").length == 226 && !has_achievement?("global")
    		award_achievement("global")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "education").length == 160 && !has_achievement?("education")
    		award_achievement("education")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(topic: "work").length == 226 && !has_achievement?("work")
    		award_achievement("work")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	elsif words.where(tier: "foundation").length == 1412 && !has_achievement?("allfoundation")
    		award_achievement("allfoundation")
    		if !has_achievement?("completetopic")
    			award_achievement("completetopic")
    		end
    	end
    end

    def misc_achievements
    	if user_words.find_by(stage: 2) != nil && !has_achievement?("stage2")
    		award_achievement("stage2")
    	elsif user_words.find_by(stage: 5) != nil && !has_achievement?("stage5")
    		award_achievement("stage5")
    	end
    end

    def one_of_each
    	all_topics = Word.select(:topic).uniq.order(:topic).map(&:topic)
    	user_topics = words.select(:topic).uniq.order(:topic).map(&:topic)
    	
    	if all_topics == user_topics && !has_achievement?("1ofeach")
    		award_achievement("1ofeach")
    	end
    end

  private

    def send_welcome_email
      WelcomeMailer.welcome_email(self).deliver_now
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]
	 # after_action :send_welcome_email, only: [:create]
	

	def index
		unless current_user.nil?
			redirect_to user_path(current_user)
		end
	end

	def show
		@user = current_user
		
		@words = @user.user_words
		@recent_words = @words.order("created_at DESC").limit(15)
		@best_words = @words.order("stage DESC").limit(15)
		@worst_words = @words.order("stage ASC").limit(15)

		@best_topics = @best_words.limit(3).map do |bw|
							bw.word.topic
						end
		@best_topics = @best_topics.uniq

		@worst_topics = @worst_words.limit(3).map do |ww|
							ww.word.topic
						end
		@worst_topics = @worst_topics.uniq

		@best_word_types = @best_words.limit(2).map do |b|
							b.word.word_type
						end
		@best_word_types = @best_word_types.uniq

		@worst_word_types = @worst_words.limit(2).map do |w|
							w.word.word_type
						end
		@worst_word_types = @worst_word_types.uniq

		@trainings = @user.trainings.order("updated_at DESC").limit(15)
		render :show

		
		@achievements = @user.achievements

	end

	   #  private

    # def send_welcome_email
    #   WelcomeMailer.welcome_email(resource).deliver_now
    #   puts "Email sent"
    # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="homepage-hero-module">

    <div class="video-container">
    	<div class="maintext">
    	<h1 style="font-size: 60px;">Learn GCSE vocabulary anywhere with daily 10-minute challenges</h1>
    	<%= button_to "Sign Up Free Now", new_user_registration_path, :method => "get", :class => "training-button" %>
    	</div>
        <div class="filter"></div>
        <video autoplay loop class="fillWidth">
            <source src="Procrastination.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="assets/videos/WEBM/Procrastination.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <h1>Text in Video Filter Div</h1>
        </video>
        <div class="poster hidden">
            <img src="./assets/videos/Snapshots/Procrastination.jpg" alt="">
        </div>
    </div>
</div>

app/views/users/show.html.erb
<body>

<div class="container-fluid user-page">
	<div class="row">
		<div class="col-lg-4 col-lg-push-4 col-sm-12 col-xs-12 training">
			<%= button_to "Start training!", new_training_path, :method => "get", :class => "training-button" %>
			<div class="recent-trainings">
				<div class="mini-header">
					<h3><%= @user.name %>'s Training Sessions</h3>
				</div>
				<div class="contents">
					<button href="#training-sessions" class="btn btn-default" data-toggle="collapse">See Most Recent Training Sessions</button>
					<div id="training-sessions" class="collapse">
					<% @trainings.each do |t| %>
						<p><%= link_to "#{t.updated_at.strftime("%d %b %y")}: #{t.name.capitalize}", training_path(t) %>
					
						<br>Topic: <%= t.topic.capitalize %>
						</p>
					<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-lg-pull-4 col-sm-12 col-xs-12 achievements">
			<div class="stat-box">
				<div class="mini-header">
					<h3>Recently Seen Words</h3>
				</div>
				<div class="contents">
					<button href="#recent-words" class="btn btn-default" data-toggle="collapse">See Latest Words</button>
					<div id="recent-words" class="collapse">
					<% @recent_words.each do |w| %>
						<p><strong class="tl-word"><%= w.word.tl %></strong>: <%= w.word.english %>
						<br><small style="color: #88D317">Stage: <% if w.stage.nil? %>
									<em style="color:red">You haven't got this word right yet!</em>
								<% else %>
									<%= w.stage %></small>
								<% end %>
						</p>
					<% end %>
				</div>
				</div>
				</div>
			<div class="trophy-cabinet">
				<div class="mini-header">
					<h3>Trophy Cabinet</h3>
				</div>
				<div class="contents">
					<h4>Days Trained In A Row: <%= @user.streak(:trainings) %></h4>
					<h4>Total Points: <%= @user.points %></h4>
					<div class="trophies">
						<% if @user.achievements %>
							<% @user.achievements.each do |a| %>
								
									<img alt="<%= a.name %>" src="/assets/<%= a.icon %>" title="<%= a.description %>">
								
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		</div>

		

		<div class="col-lg-4 col-sm-12 col-xs-12 stats">
			<div class="stat-box">
				<div class="mini-header">
					<h3>My Strengths</h3>
				</div>
				<div class="contents">
					<button href="#top-words" class="btn btn-default" data-toggle="collapse">Top Words</button>
					<div id="top-words" class="collapse">
						<% @best_words.each do |bw| %>
							<p><strong class="tl-word"><%= bw.word.tl %></strong>: <%= bw.word.english %>
							<br><small style="color: #88D317">Stage: <% if bw.stage.nil? %>
											<em style="color:red">You haven't got this word right yet!</em>
										<% else %>
											<%= bw.stage %></small>
										<% end %></p>
							<% end %>
					</div>
					<br><br>
					<button href="#top-topics" class="btn btn-default" data-toggle="collapse">Top Topics</button>
					<div id="top-topics" class="collapse">
					
						<% @best_topics.each do |bt| %>
							<p><%= bt %></p>
						<% end %>
					</div>
					<br><br>
					<button href="#top-types" class="btn btn-default" data-toggle="collapse">Top Word Types</button>
					<div id="top-types" class="collapse">
					
						<% @best_word_types.each do |bwt| %>
							<p><%= bwt %></p>
						<% end %>
					</div>
					</div>
				</div>

			<div class="stat-box">
				<div class="mini-header">
					<h3>I Need To Improve...</h3>
				</div>
				<div class="contents">
					<button href="#worst-words" class="btn btn-default" data-toggle="collapse">Words To Work On</button>
					<div id="worst-words" class="collapse">
						<% @worst_words.each do |ww| %>
							<p><strong class="tl-word"><%= ww.word.tl %></strong>: <%= ww.word.english %>
							<br><small style="color: #88D317">Stage: <% if ww.stage.nil? %>
											<em style="color:red">You haven't got this word right yet!</em>
										<% else %>
											<%= ww.stage %></small>
										<% end %></p>
						<% end %>
					</div>
					<br><br>
					<button href="#worst-topics" class="btn btn-default" data-toggle="collapse">Topics To Work On</button>
					<div id="worst-topics" class="collapse">

						<% @worst_topics.each do |wt| %>
							<p><%= wt %></p>
						<% end %>
					</div>
					<br><br>
					<button href="#worst-types" class="btn btn-default" data-toggle="collapse">Word Types To Work On</button>
					<div id="worst-types" class="collapse">

						<% @worst_word_types.each do |wwt| %>
							<p><%= wwt%></p>
						<% end %>
					</div>
					</div>
				</div>
		</div>
	</div>
</div>

</body>




	